### PR TITLE
Verifier

### PR DESCRIPTION
**Pull request by ll-nick**
Alright, here is a very simple verifier that makes sure our command output does not try running into walls.

76f1f5cec05ebc5268c48fa316b35fa448d94bf7 This one is a little ugly, check the commit description for details. My proposal would be the following: After all merge request have been worked on and the demo branch is in a good state, I'd remove the `DIRECTION::LAST` enum altogether. Since we replaced `DoNothing` with `StayInPlace` we don't really need it anymore and it does not play well with the costEstimator.

### CODE REVIEW

**Comment by orzechow** [comment]
Rebased on top of latest #36

**Comment by orzechow** [comment]
No unit tests? :sob:

**Review by orzechow — CHANGES_REQUESTED** [review]
Minimalistic, but should be good 👍

Only thing: please add a unit test 🥺

**Comment by ll-nick** [comment]
@orzechow Any objections to remove `Direction::LAST`? I would include that into this PR so that we don't need the hacky commit described above.

**Comment by orzechow** [comment]
> @orzechow Any objections to removing `Direction::LAST`? I would include that into this PR so that we don't need the hacky commit described above.

I'm fine with that 👍

**Comment by ll-nick** [comment]
Alrighty, there's a test now. If it seems familiar to you, that's because it is :stuck_out_tongue_closed_eyes:

**Comment by ll-nick** [comment]
Rebased on current #38

**Comment by orzechow** [comment]
> Alrighty, there's a test now. If it seems familiar to you, that's because it is 😝

:smirk:

**Review by orzechow — APPROVED** [review]
Thanks a lot! Let's merge :tada:

**Pull request merged**
