### PR TITLE
Add website

### LINKED ISSUE #33: Add project website
Hosting a static website via github.io shouldn't be a huge amount of effort but is way cooler than having just the readme.

### PR DESCRIPTION
**Pull request by orzechow**
This closes #33 

image

### CODE REVIEW

**Comment by orzechow** [comment]
@ll-nick Ready for review and merging.

We should change the [GitHub Pages branch setting](https://github.com/KIT-MRT/arbitration_graphs/settings/pages) to `main` after merging.

**Review by ll-nick — APPROVED** [review]
Looks really good and the docker setup works (almost) like a charm, thank you! :rocket: 
Also very nice work in keeping the root directory clean. :broom: 

Maybe you have an idea for these two things, otherwise feel free to merge :)
1. The browser tab title is currently: `ARBITRATION_GRAPHS | Arbitration Graphs`
I tried changing it using a `title:` in the `_config.yml` but that only affects the second half. I did not manage to change the first half. I would imagine it being either only `Arbitration Graphs` or something like `Arbitration Graphs | Home`  since we want to have different pages.
2. About the docker setup: I did not manage to get it to work at first because my root directory contained the compile_commands.json. Since that is a symlink generated in the dev container, it points to something like `/home/blinky` which is apparently something jekyll is not able not handle, even if you add it to the `exclude:` setting. I solved it by removing the link, not sure if there is a better option.

**Comment by ll-nick** [comment]
Oh and once we solved #49, we should definitely add a `favicon` :wink:

**Comment by orzechow** [comment]
>     1. The browser tab title is currently: `ARBITRATION_GRAPHS | Arbitration Graphs`
>        I tried changing it using a `title:` in the `_config.yml` but that only affects the second half. I did not manage to change the first half. I would imagine it being either only `Arbitration Graphs` or something like `Arbitration Graphs | Home`  since we want to have different pages.

Done, see ad495ac


>     2. About the docker setup: I did not manage to get it to work at first because my root directory contained the compile_commands.json. Since that is a symlink generated in the dev container, it points to something like `/home/blinky` which is apparently something jekyll is not able not handle, even if you add it to the `exclude:` setting. I solved it by removing the link, not sure if there is a better option.

I don't know how you've setup your dev container. But when using our docker compose setups, the `compile_commands.json` should be generated into the build folder and shouldn't be a symlink.
Maybe, you had issues with the demo build setup. You can tell your cmake to lookout for

**Comment by ll-nick** [comment]
Yeah, nevermind the compile commands thing. I am honestly not sure why the link was even there in the first place, my LSP works just fine without it 🤷‍♂️

**Pull request merged**
